#:schema node_modules/wrangler/config-schema.json
name = "page"
compatibility_date = "2024-09-09"
pages_build_output_dir = "./build/client"

[[services]]
binding = "SERVICE"
service = "worker"
entrypoint = "ExampleService"
